import { EB_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-eb-garamond",
})

export const metadata = {
  title: "Oranic Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light' >
      <body
        className={`${ebGaramond.variable} font-garamond antialiased`}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
